title: My Awesome Blog
description: This is my awesome blog with a very detailed, specific description.

url: "https://jct03.github.io/csci340lab5"
paginate_path: "/blog/page:num/"
permalink: "/blog/:title/"

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: "{{ '/' | prepend: site.url }}"
    - title: About
      url: "{{ '/about/' | prepend: site.url }}"

social:
    github: jct03
    email: colliertenisonjt@hendrix.edu
    linkedin: jacob-collier-tenison