title: My Awesome Blog
description: This is my awesome blog with a very detailed, specific description.

url: https://jct03.github.io/csci340lab5/
paginate_path: "csci340lab5/blog/page:num/"
permalink: csci340lab5/blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: index.html
    - title: About
      url: csci340lab5/about/index.html

social:
    github: jct03
    email: colliertenisonjt@hendrix.edu
    linkedin: jacob-collier-tenison

